//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by APhysXLab.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_DRAGOPT            101
#define ID_INDICATOR_DRVMODE            102
#define ID_INDICATOR_CURSTATE           103
#define ID_INDICATOR_SHOOTMODE          104
#define ID_INDICATOR_SHOOTTYPE          105
#define IDR_MAINFRAME                   128
#define IDR_APHYSXTYPE                  129
#define IDD_TRNBUILDER                  130
#define IDD_SHOOTSCALE                  131
#define IDD_FLAGS_SETTING               132
#define IDD_FFEDIT                      133
#define IDR_MENU_POP                    134
#define IDC_EDIT_TRNFILE                1000
#define IDC_BTN_BROWSE                  1001
#define IDC_EDIT_TRNINFO                1002
#define IDC_PROGRESS                    1003
#define IDC_SCALE                       1004
#define IDC_SPEED                       1005
#define IDC_STATIC_MODEL                1008
#define IDC_STATIC_CC                   1009
#define IDC_CHECK_PF                    1010
#define IDC_CHECK_SF                    1011
#define IDC_CHECK_CCSLIDE               1012
#define IDC_CHECK_CCPF                  1013
#define IDC_CHECK_CCSF                  1014
#define IDC_CHECK_CCFO                  1015
#define IDC_CHECK_CCFC                  1016
#define IDC_CHECK_HASPB                 1017
#define IDC_CHECK_CAA                   1018
#define IDC_STATIC_PEOPLE               1019
#define IDC_CHECK_ISMA                  1020
#define IDC_CHECK_ISNPC                 1021
#define IDC_CHECK_HASCC                 1022
#define IDC_STATIC_NPCACTION            1023
#define IDC_RADIO_DANCE                 1024
#define IDC_RADIO_WALKAROUND            1025
#define IDC_RADIO_WALKCAMERA            1026
#define IDC_RADIO_WALKXAXIS             1027
#define IDC_STATIC_CHANNEL              1028
#define IDC_RADIO_CNL_CMN               1029
#define IDC_RADIO_CNL_IDP               1030
#define IDC_RADIO_CNL_IDPCMN            1031
#define IDC_CHECK_HASLWCC               1032
#define IDC_COMBO_FFTYPE                1034
#define IDC_RADIO_STBOX                 1036
#define IDC_RADIO_STSPHERE              1037
#define IDC_RADIO_STCAPSULE             1038
#define IDC_RADIO_STCONVEX              1039
#define IDC_EDIT_SSX                    1040
#define IDC_EDIT_SSY                    1041
#define IDC_EDIT_SSZ                    1042
#define IDC_EDIT_FILENAME               1043
#define IDC_STATIC_R                    1044
#define IDC_STATIC_H                    1045
#define IDC_BTN_LOAD                    1046
#define IDC_RADIO_CORCAR                1047
#define IDC_RADIO_CORSPH                1048
#define IDC_RADIO_CORCYL                1049
#define IDC_RADIO_CORTOR                1050
#define IDC_COMBO_RB                    1051
#define IDC_COMBO_CLOTH                 1052
#define IDC_COMBO_FLUID                 1053
#define IDC_COMBO_SB                    1054
#define IDC_EDIT_RB                     1055
#define IDC_EDIT_CLOTH                  1056
#define IDC_EDIT_FLUID                  1057
#define IDC_EDIT_SB                     1058
#define IDC_STATIC_WIND                 1059
#define IDC_STATIC_WFD                  1060
#define IDC_STATIC_WX                   1061
#define IDC_STATIC_WY                   1062
#define IDC_STATIC_WZ                   1063
#define IDC_EDIT_WFDX                   1064
#define IDC_EDIT_WFDY                   1065
#define IDC_EDIT_WFDZ                   1066
#define IDC_STATIC_WWT                  1067
#define IDC_EDIT_WWT                    1068
#define IDC_STATIC_WRT                  1069
#define IDC_EDIT_WRT                    1070
#define IDC_STATIC_WCT                  1071
#define IDC_EDIT_WCT                    1072
#define IDC_STATIC_VTV                  1073
#define IDC_STATIC_VORTEX               1074
#define IDC_STATIC_VTVM                 1075
#define IDC_STATIC_VTR                  1076
#define IDC_STATIC_VTRM                 1077
#define IDC_EDIT_VTV                    1078
#define IDC_EDIT_VTVM                   1079
#define IDC_EDIT_VTR                    1080
#define IDC_EDIT_VTRM                   1081
#define IDC_STATIC_VCF                  1082
#define IDC_STATIC_VEF                  1083
#define IDC_STATIC_VES                  1084
#define IDC_EDIT_VCF                    1085
#define IDC_EDIT_VEF                    1086
#define IDC_EDIT_VES                    1087
#define IDC_EDIT_VN                     1088
#define IDC_STATIC_VN                   1089
#define IDC_STATIC_EXPLOSION            1090
#define IDC_STATIC_ECF                  1091
#define IDC_STATIC_ER                   1092
#define IDC_STATIC_ELT                  1093
#define IDC_STATIC_EQFO                 1094
#define IDC_EDIT_ECF                    1095
#define IDC_EDIT_ER                     1096
#define IDC_EDIT_ELT                    1097
#define IDC_EDIT_EQFO                   1098
#define IDC_STATIC_GRAVITATION          1099
#define IDC_STATIC_GG                   1100
#define IDC_STATIC_GX                   1101
#define IDC_STATIC_GY                   1102
#define IDC_STATIC_GZ                   1103
#define IDC_EDIT_GX                     1104
#define IDC_EDIT_GY                     1105
#define IDC_EDIT_GZ                     1106
#define IDC_STATIC_BUOYANCY             1107
#define IDC_STATIC_VACUUM               1108
#define IDC_STATIC_BD                   1109
#define IDC_EDIT_BD                     1110
#define IDC_STATIC_WCD                  1111
#define IDC_EDIT_WCD                    1112
#define IDC_BTN_BINDMA                  1113
#define IDC_STATIC_BINDMA               1114
#define IDC_STATIC_BOSSAURA             1115
#define IDC_EDIT_BAFV                   1116
#define IDC_EDIT_BAR                    1117
#define IDC_STATIC_BAFV                 1118
#define IDC_STATIC_BAR                  1119
#define ID_EDIT_ADDTERRAIN              32771
#define ID_EDIT_ADDSTATICOBJ            32772
#define ID_EDIT_ADDSMD                  32773
#define ID_EDIT_ADDPHYSXGFX             32774
#define ID_EDIT_ADDLASTOBJ              32775
#define ID_EDIT_PHYSXTRNGEN             32776
#define ID_EDIT_DRAGANDMOVE             32777
#define ID_EDIT_DRAGANDROTATE           32778
#define ID_FILE_RESET                   32779
#define ID_MODE_EDIT                    32780
#define ID_MODE_SIMULATE                32781
#define ID_MODE_PLAY                    32782
#define ID_MODE_PHYSXPROFILE            32783
#define ID_MODE_PHYSXDEBUGRENDER        32784
#define ID_MODE_PX_PROFILE              32785
#define ID_MODE_PX_DEBUG                32786
#define ID_VIEW_WIRE                    32787
#define ID_MODE_DVN_ANIMATION           32789
#define ID_MENUITEM32790                32790
#define ID_MODE_DVN_PARTPHYSX           32791
#define ID_MODE_DVN_PUREPHYSX           32792
#define ID_EDIT_DRAGANDSCALE            32793
#define ID_MODE_C_FOLLOWING             32794
#define ID_EDIT_ADDECM                  32795
#define ID_EDIT_SCALE                   32796
#define ID_FILE_SAVEAS                  32797
#define ID_EDIT_ADDPHYSXFF              32798
#define ID_EDIT_PHYSXFFMAKER            32799
#define ID_MODE_PHYSXHW                 32800
#define ID_MENUITEM32801                32801
#define ID_MENU_EDITMOD                 32802
#define ID_FILE_CHF2CHB                 32803
#define ID_EDIT_ADDCHB                  32804
#define ID_FILE_RECENT0                 60000
#define ID_FILE_RECENT1                 60001
#define ID_FILE_RECENT2                 60002
#define ID_FILE_RECENT3                 60003
#define ID_FILE_RECENT4                 60004
#define ID_FILE_RECENT                  65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
